/* N1 Forex Academy — module catalogue.

   GENERATED FILE. Do not edit by hand — run:  node tools/build-catalog.mjs

   Lightweight metadata for every module, loaded eagerly so the journey, the
   library and the route guards can render without fetching module content.
   Full content lives in content/modules/mN.js and loads on demand. */
window.CATALOG = [
  { id: 1, track: "forex", title: "What the Forex Market Actually Is",
    tagline: "The market, its participants, and why a price moves at all — before any chart appears.",
    level: "Foundation", duration: "90 min", slides: 11, quiz: 6 },
  { id: 2, track: "forex", title: "Pairs, Quotes, Pips and Lots",
    tagline: "The arithmetic of a trade. Get this wrong and every risk calculation later in the course is wrong too.",
    level: "Foundation", duration: "120 min", slides: 10, quiz: 6 },
  { id: 3, track: "forex", title: "Orders, Leverage and Margin",
    tagline: "How a trade is actually placed and financed — and the exact mechanism by which accounts get wiped out.",
    level: "Foundation", duration: "120 min", slides: 10, quiz: 6 },
  { id: 4, track: "forex", title: "Brokers, Platforms and Account Setup",
    tagline: "Choosing a counterparty you can get your money back from, and configuring a workspace you can actually work in.",
    level: "Foundation", duration: "90 min", slides: 10, quiz: 6 },
  { id: 5, track: "forex", title: "Sessions, Timing and Volatility",
    tagline: "The same strategy wins in one hour and loses in another. When you trade is a strategy decision, not a convenience.",
    level: "Core skill", duration: "90 min", slides: 8, quiz: 6 },
  { id: 6, track: "forex", title: "Reading Price — Candlesticks and Structure",
    tagline: "Learning to describe what a chart is doing, out loud, before ever deciding what to do about it.",
    level: "Core skill", duration: "120 min", slides: 9, quiz: 6 },
  { id: 7, track: "forex", title: "Levels — Support, Resistance and Liquidity",
    tagline: "Where price is likely to react, why it reacts there, and how to mark levels that are actually useful.",
    level: "Core skill", duration: "120 min", slides: 9, quiz: 6 },
  { id: 8, track: "forex", title: "Indicators — What They Do and What They Cannot Do",
    tagline: "Every indicator is arithmetic on past prices. Knowing exactly which arithmetic tells you exactly what it can and cannot say.",
    level: "Core skill", duration: "120 min", slides: 10, quiz: 6 },
  { id: 9, track: "forex", title: "Fundamentals, News and Why Currencies Move",
    tagline: "The forces that actually drive a currency over weeks and months — and how to survive the ten seconds around a release.",
    level: "Core skill", duration: "90 min", slides: 9, quiz: 6 },
  { id: 10, track: "forex", title: "Risk Management and Position Sizing",
    tagline: "The most important module in this course. Everything before it was preparation for this.",
    level: "Advanced", duration: "150 min", slides: 11, quiz: 6 },
  { id: 11, track: "forex", title: "Building a Strategy and Writing the Plan",
    tagline: "Turning everything so far into a specific, written, testable set of rules that another person could follow.",
    level: "Advanced", duration: "120 min", slides: 10, quiz: 6 },
  { id: 12, track: "forex", title: "Testing, Journaling, Psychology and Automation",
    tagline: "Proving whether the plan works, learning from what it does, and deciding whether to automate it.",
    level: "Advanced", duration: "150 min", slides: 11, quiz: 6 },
  { id: 101, track: "equities", title: "What a Share Actually Is",
    tagline: "You stop betting on a relative price and start owning a claim on a real business.",
    level: "Foundation", duration: "90 min", slides: 7, quiz: 5 },
  { id: 102, track: "equities", title: "How Shares Are Priced and Traded",
    tagline: "Order books, liquidity and settlement — the mechanics that decide what you actually pay.",
    level: "Foundation", duration: "90 min", slides: 7, quiz: 5 },
  { id: 103, track: "equities", title: "Owning Shares versus Trading CFDs",
    tagline: "The same company, two completely different products — and only one of them makes you an owner.",
    level: "Core skill", duration: "90 min", slides: 7, quiz: 5 },
  { id: 104, track: "equities", title: "Reading a Company by the Numbers",
    tagline: "What the published figures tell you, what they hide, and why a cheap-looking share is often cheap for a reason.",
    level: "Core skill", duration: "120 min", slides: 7, quiz: 5 },
  { id: 105, track: "equities", title: "Earnings, Catalysts and Corporate Actions",
    tagline: "The scheduled and unscheduled events that move a share far more than any chart pattern.",
    level: "Core skill", duration: "90 min", slides: 6, quiz: 5 },
  { id: 106, track: "equities", title: "Indices, Sectors and What Moves Together",
    tagline: "Most of a share's daily move has nothing to do with the company itself.",
    level: "Core skill", duration: "90 min", slides: 6, quiz: 5 },
  { id: 107, track: "equities", title: "Risk Without Leverage",
    tagline: "Position sizing when there is no margin, no pip value, and gaps arrive overnight.",
    level: "Advanced", duration: "120 min", slides: 6, quiz: 5 },
  { id: 108, track: "equities", title: "Building an Equity Approach",
    tagline: "Turning everything into a written process — and an honest comparison with the forex track.",
    level: "Advanced", duration: "120 min", slides: 7, quiz: 5 },
  { id: 201, track: "bonds", title: "What a Bond Actually Is",
    tagline: "You stop owning and start lending — and the whole risk profile inverts.",
    level: "Foundation", duration: "90 min", slides: 6, quiz: 5 },
  { id: 202, track: "bonds", title: "Price, Yield and the Inverse Relationship",
    tagline: "The single most important mechanic in fixed income, and the one that surprises everyone.",
    level: "Core skill", duration: "120 min", slides: 6, quiz: 5 },
  { id: 203, track: "bonds", title: "Duration and Interest Rate Risk",
    tagline: "Why a twenty-year bond is a completely different risk from a two-year one with the same coupon.",
    level: "Core skill", duration: "90 min", slides: 6, quiz: 5 },
  { id: 204, track: "bonds", title: "Credit Risk and Ratings",
    tagline: "The extra yield a company pays is the market's estimate of how likely it is to fail.",
    level: "Core skill", duration: "90 min", slides: 6, quiz: 5 },
  { id: 205, track: "bonds", title: "The Yield Curve",
    tagline: "One chart that shows what the market expects rates, growth and inflation to do.",
    level: "Advanced", duration: "90 min", slides: 6, quiz: 5 },
  { id: 206, track: "bonds", title: "Bonds, Rates and Currencies — Closing the Loop",
    tagline: "The three markets you have studied are one system. This module shows you the wiring.",
    level: "Advanced", duration: "120 min", slides: 7, quiz: 5 },
  { id: 301, track: "futures", title: "What a Futures Contract Actually Is",
    tagline: "An obligation with a date on it — standardised, exchange-traded, and guaranteed by someone who has never met you.",
    level: "Derivatives", duration: "75 min", slides: 7, quiz: 5 },
  { id: 302, track: "futures", title: "Margin, Daily Settlement and Real Cash",
    tagline: "Your profit and loss stops being a number on a screen and starts being money moving in and out of your account every single evening.",
    level: "Derivatives", duration: "90 min", slides: 6, quiz: 5 },
  { id: 303, track: "futures", title: "Expiry, Rollover and the Shape of the Curve",
    tagline: "Every contract dies on a known date. What that costs you depends on the shape of a curve nobody shows you on the chart.",
    level: "Derivatives", duration: "90 min", slides: 6, quiz: 5 },
  { id: 304, track: "futures", title: "Who Is Actually On The Other Side",
    tagline: "Most of the money in this market is not trying to make money. Understanding why changes how you read it.",
    level: "Derivatives", duration: "75 min", slides: 6, quiz: 5 },
  { id: 305, track: "futures", title: "Risk and Building a Futures Approach",
    tagline: "The same risk policy you already signed, extended for whole contracts, cash settlement and a market that trades while you sleep.",
    level: "Derivatives", duration: "90 min", slides: 6, quiz: 5 },
  { id: 401, track: "options", title: "The Right, Not the Obligation",
    tagline: "One side gets to choose. Everything else about options follows from that single asymmetry.",
    level: "Derivatives", duration: "90 min", slides: 7, quiz: 5 },
  { id: 402, track: "options", title: "What an Option Is Actually Worth",
    tagline: "Every premium splits into two parts. One is arithmetic you can check; the other is everything anyone believes about the future.",
    level: "Derivatives", duration: "80 min", slides: 5, quiz: 5 },
  { id: 403, track: "options", title: "Time Decay — The Clock You Are Trading Against",
    tagline: "Extrinsic value must reach zero by expiry. Every day you hold a bought option, some of it goes, and it goes faster near the end.",
    level: "Derivatives", duration: "85 min", slides: 6, quiz: 5 },
  { id: 404, track: "options", title: "Volatility — What You Are Really Trading",
    tagline: "Two people can agree exactly where the price is going and still disagree on what the option is worth. Volatility is the argument.",
    level: "Derivatives", duration: "90 min", slides: 6, quiz: 5 },
  { id: 405, track: "options", title: "The Greeks, In Plain Language",
    tagline: "Five numbers that answer five questions you already know to ask. No mathematics required to use them.",
    level: "Derivatives", duration: "80 min", slides: 6, quiz: 5 },
  { id: 406, track: "options", title: "Structures, Assignment and Building an Options Approach",
    tagline: "A handful of structures worth knowing, the obligation that can arrive uninvited, and an honest answer about whether this belongs in your account.",
    level: "Derivatives", duration: "95 min", slides: 6, quiz: 5 },
  { id: 501, track: "crypto", title: "What a Crypto Asset Actually Is",
    tagline: "A ledger, a token, and a question worth answering before anything else: what exactly would you own?",
    level: "Digital Assets", duration: "80 min", slides: 6, quiz: 5 },
  { id: 502, track: "crypto", title: "Custody, Exchanges and How People Actually Lose Everything",
    tagline: "More retail money has been lost here to custody failures and irreversible mistakes than to being wrong about the price.",
    level: "Digital Assets", duration: "85 min", slides: 6, quiz: 5 },
  { id: 503, track: "crypto", title: "What Actually Moves the Price",
    tagline: "Thin books, reflexive flows and a market that trades every hour of every day — including the ones where nobody is watching.",
    level: "Digital Assets", duration: "80 min", slides: 6, quiz: 5 },
  { id: 504, track: "crypto", title: "Perpetuals, Funding and Liquidation",
    tagline: "A futures contract that never expires, a fee that keeps it tethered, and an automatic closure that does not wait for you.",
    level: "Digital Assets", duration: "85 min", slides: 6, quiz: 5 },
  { id: 505, track: "crypto", title: "Risk in an Unregulated Market, and Closing the Course",
    tagline: "The last module of six tracks. One policy, extended a fifth time — and an honest answer about what all of this was for.",
    level: "Digital Assets", duration: "95 min", slides: 6, quiz: 5 },
  { id: 601, track: "commodities", title: "What a Commodity Actually Is",
    tagline: "The only thing in this course that has to be dug up, grown, shipped and stored — and every one of those verbs costs money.",
    level: "Physical Markets", duration: "75 min", slides: 5, quiz: 5 },
  { id: 602, track: "commodities", title: "Inventory, Weather and What Actually Moves It",
    tagline: "Boring published numbers beat compelling stories in this market more reliably than in any other you have studied.",
    level: "Physical Markets", duration: "80 min", slides: 6, quiz: 5 },
  { id: 603, track: "commodities", title: "Three Families, Not One Asset Class",
    tagline: "Energy, metals and agriculture share a shelf and almost nothing else. Treating them as one thing produces confident nonsense.",
    level: "Physical Markets", duration: "80 min", slides: 6, quiz: 5 },
  { id: 604, track: "commodities", title: "Four Ways In, Each With a Cost",
    tagline: "You have decided a commodity is going up. Now choose how — because every route charges you differently and one of them is not really the commodity at all.",
    level: "Physical Markets", duration: "85 min", slides: 6, quiz: 5 },
  { id: 605, track: "commodities", title: "Risk and Building a Commodities Approach",
    tagline: "The sixth extension of one risk policy, and an honest answer about how narrow a place this market should have.",
    level: "Physical Markets", duration: "85 min", slides: 5, quiz: 5 },
  { id: 701, track: "spreadbet", title: "A Wrapper, Not a Market",
    tagline: "Spread betting is not an asset class. It is a different container for markets you already understand — and the container changes the arithmetic without changing the risk.",
    level: "Wrappers", duration: "70 min", slides: 5, quiz: 5 },
  { id: 702, track: "spreadbet", title: "Sizing When the Ticket Hides the Position",
    tagline: "One formula, used every time, converts the friendliest sizing vocabulary in trading back into something you can actually judge.",
    level: "Wrappers", duration: "75 min", slides: 5, quiz: 5 },
  { id: 703, track: "spreadbet", title: "Guaranteed Stops and What Protection Costs",
    tagline: "The one genuine innovation in this wrapper: a stop that actually holds across a gap. It is not free, and knowing what it is worth is the skill.",
    level: "Wrappers", duration: "70 min", slides: 6, quiz: 5 },
  { id: 704, track: "spreadbet", title: "Tax, Suitability and the End of the Course",
    tagline: "The most misunderstood feature of this wrapper, stated honestly — and then the close of all eight tracks.",
    level: "Wrappers", duration: "80 min", slides: 6, quiz: 5 },
  { id: 801, track: "automation", title: "What an EA Actually Is",
    tagline: "An execution engine, not a strategy. It will follow your rules perfectly, including the wrong ones.",
    level: "Automation", duration: "70 min", slides: 5, quiz: 5 },
  { id: 802, track: "automation", title: "The Three Functions That Matter",
    tagline: "MQL is a large language and you need a small corner of it. This is that corner.",
    level: "Automation", duration: "90 min", slides: 5, quiz: 5 },
  { id: 803, track: "automation", title: "Translating Your Setup Into Code",
    tagline: "The five components you wrote in Module 11 become five functions. This is translation, not invention.",
    level: "Automation", duration: "100 min", slides: 5, quiz: 5 },
  { id: 804, track: "automation", title: "Position Sizing in Code",
    tagline: "The one place a beginner's EA is most often wrong, and it is always the same wrong: a hard-coded lot size.",
    level: "Automation", duration: "90 min", slides: 5, quiz: 5 },
  { id: 805, track: "automation", title: "Testing It Honestly",
    tagline: "The strategy tester will tell you almost anything you want to hear. Module 12's biases, plus the ones automation adds.",
    level: "Automation", duration: "95 min", slides: 5, quiz: 5 },
  { id: 806, track: "automation", title: "Going Live, and the End of the Programme",
    tagline: "Every failure that only exists once real money is connected — and then the close of all nine tracks.",
    level: "Automation", duration: "95 min", slides: 6, quiz: 5 }
];
